-- -- disable netrw at the very start of your init.lua
--   vim.g.loaded_netrw = 1
--   vim.g.loaded_netrwPlugin = 1

-- -- set termguicolors to enable highlight groups
--   vim.opt.termguicolors = true

-- require'nvim-tree'.setup {
--       view = {
--         width = 35,
--         side = "left",
--         signcolumn = "no",
--     },
--     renderer = {
--         root_folder_label = true,
--         icons = {
--             show = {
--                 file = true,
--                 folder = true,
--                 folder_arrow = true,
--                 git = false
--             }
--   }
--     },
--     git = {
--   enable = true,
--   ignore = false,
--   timeout = 500,
-- },
--     diagnostics = {
--     enable = true,
--     show_on_dirs = true,
--     icons = {
--       hint = "",
--       info = "",
--       warning = "",
--       error = "",
--     },
--   }
-- }


